import type { NextPage } from 'next';
import Head from 'next/head';
import HomeTemplate from 'components/Template/Home';
import Layout from 'components/Organisms/Layout';

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>Kevin Rivas</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeTemplate />
    </Layout>
  );
};

export default Home;
